blank_issues_enabled: false

contact_links:
  - name: Questions & Support
    url: https://github.com/irfanghat/spark-connect-cpp/discussions
    about: Ask questions or request community assistance.
