name: "Build and Test"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      spark:
        image: apache/spark:4.0.0-scala2.13-java21-r-ubuntu
        ports:
          - 15002:15002
        options: >-
          --name spark_server
          --health-cmd "nc -z localhost 15002"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          SPARK_NO_DAEMONIZE: "true"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        chmod +x install_deps.sh
        sudo ./install_deps.sh

    - name: Check dependencies
      run: make check-deps

    - name: Build Spark Connect Client Library
      run: make all

    - name: Build Tests
      run: make build-tests

    - name: Run Tests
      run: make test